import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'

// Custom plugin: generates firebase-messaging-sw.js into /public at build/dev time
// using env vars so nothing sensitive is hardcoded in the repo.
function firebaseSwPlugin() {
  return {
    name: 'firebase-messaging-sw',
    buildStart() {
      // loadEnv reads from .env — works in both dev and build
    },
    configResolved(config) {
      const env = config.env

      const swContent = `// Auto-generated by vite.config.js — DO NOT EDIT MANUALLY
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: "${env.VITE_FIREBASE_API_KEY}",
  authDomain: "${env.VITE_FIREBASE_AUTH_DOMAIN}",
  projectId: "${env.VITE_FIREBASE_PROJECT_ID}",
  storageBucket: "${env.VITE_FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${env.VITE_FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${env.VITE_FIREBASE_APP_ID}",
  measurementId: "${env.VITE_FIREBASE_MEASUREMENT_ID}"
});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  console.log('[SW] Background message received:', payload);
  const { title, body, icon } = payload.notification || {};
  self.registration.showNotification(title || '\\uD83D\\uDD14 Market-U', {
    body: body || 'You have a new notification',
    icon: icon || '/icon.png',
    badge: '/icon.png',
    tag: 'market-u-interest',
    data: payload.data || {},
  });
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow('/notifications');
      }
    })
  );
});
`

      const outPath = path.resolve(config.root, 'public', 'firebase-messaging-sw.js')
      fs.writeFileSync(outPath, swContent, 'utf-8')
      console.log('✅ firebase-messaging-sw.js generated from env vars')
    }
  }
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  return {
    plugins: [react(), firebaseSwPlugin()],
    define: {
      // Make all VITE_ env vars available
    }
  }
})
