import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'

function firebaseSwPlugin() {
  return {
    name: 'firebase-messaging-sw',
    configResolved(config) {
      const env = config.env

      const swContent = `// Auto-generated by vite.config.js — DO NOT EDIT MANUALLY
// Combined Service Worker (Offline Caching + Firebase Cloud Messaging)

importScripts('https://www.gstatic.com/firebasejs/12.19.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/12.19.0/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: "${env.VITE_FIREBASE_API_KEY}",
  authDomain: "${env.VITE_FIREBASE_AUTH_DOMAIN}",
  projectId: "${env.VITE_FIREBASE_PROJECT_ID}",
  storageBucket: "${env.VITE_FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${env.VITE_FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${env.VITE_FIREBASE_APP_ID}",
  measurementId: "${env.VITE_FIREBASE_MEASUREMENT_ID}"
});

const messaging = firebase.messaging();

// Handle FCM background messages
messaging.onBackgroundMessage((payload) => {
  console.log('[SW] onBackgroundMessage:', payload);

  const title = (payload.notification && payload.notification.title) || '🛍️ Market-U';
  const body = (payload.notification && payload.notification.body) || 'Buy from Market-U today';
  const tag = (payload.notification && payload.notification.tag) || (payload.data && payload.data.tag) || 'market-u-notification';
  const targetUrl = (payload.fcmOptions && payload.fcmOptions.link) || (payload.data && (payload.data.url || payload.data.link)) || '/market';

  self.registration.showNotification(title, {
    body: body,
    icon: '/icon.png',
    badge: '/icon.png',
    vibrate: [200, 100, 200],
    requireInteraction: false,
    tag: tag,
    data: { url: targetUrl, ...payload.data },
  });
});

// Open app to target URL when notification is clicked
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] notificationclick');
  event.notification.close();
  const targetUrl = (event.notification.data && (event.notification.data.url || event.notification.data.link)) || '/market';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus();
          // Post message for smooth client-side React Router navigation
          client.postMessage({ type: 'NAVIGATE', url: targetUrl });
          return;
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })
  );
});

// ── Offline Caching (PWA Caches) ──────────────────────────────────────────────
const CACHE_NAME = 'market-u-v8';
const ASSETS_TO_CACHE = ['/', '/index.html', '/icon.png', '/manifest.json'];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      cache.addAll(ASSETS_TO_CACHE).catch(err => console.warn('[SW] Cache addAll failed:', err))
    )
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  // Only cache GET requests
  if (event.request.method !== 'GET') return;
  
  // Navigation requests (HTML): network-first, fallback to cache for offline support
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .then((res) => {
          if (res.status === 200) {
            const resClone = res.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(event.request, resClone));
          }
          return res;
        })
        .catch(() => caches.match(event.request).then((cached) => cached || caches.match('/index.html')))
    );
    return;
  }
  
  // Other assets: network-first, fallback to cache
  event.respondWith(
    fetch(event.request).catch(() => caches.match(event.request))
  );
});
`

      const outPath = path.resolve(config.root, 'public', 'sw.js')
      fs.writeFileSync(outPath, swContent, 'utf-8')
      console.log('✅ sw.js generated from env vars')
    }
  }
}

export default defineConfig(() => {
  return {
    base: '/',
    plugins: [react(), firebaseSwPlugin()],
    build: {
      outDir: 'dist',
      emptyOutDir: true,
      chunkSizeWarningLimit: 2000,
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('node_modules')) {
              if (id.includes('firestore')) {
                return 'vendor-firestore';
              }
              if (id.includes('firebase')) {
                return 'vendor-firebase';
              }
              if (id.includes('react-dom') || id.includes('react-router-dom') || id.includes('/react/')) {
                return 'vendor-react';
              }
              if (id.includes('lucide-react') || id.includes('react-icons')) {
                return 'vendor-icons';
              }
            }
          },
        },
      },
      rolldownOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('node_modules')) {
              if (id.includes('firestore')) {
                return 'vendor-firestore';
              }
              if (id.includes('firebase')) {
                return 'vendor-firebase';
              }
              if (id.includes('react-dom') || id.includes('react-router-dom') || id.includes('/react/')) {
                return 'vendor-react';
              }
              if (id.includes('lucide-react') || id.includes('react-icons')) {
                return 'vendor-icons';
              }
            }
          },
        },
      },
    },
  }
})
