import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'

function firebaseSwPlugin() {
  return {
    name: 'firebase-messaging-sw',
    configResolved(config) {
      const env = config.env

      const swContent = `// Auto-generated by vite.config.js — DO NOT EDIT MANUALLY
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: "${env.VITE_FIREBASE_API_KEY}",
  authDomain: "${env.VITE_FIREBASE_AUTH_DOMAIN}",
  projectId: "${env.VITE_FIREBASE_PROJECT_ID}",
  storageBucket: "${env.VITE_FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${env.VITE_FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${env.VITE_FIREBASE_APP_ID}",
  measurementId: "${env.VITE_FIREBASE_MEASUREMENT_ID}"
});

const messaging = firebase.messaging();

// Handle FCM background messages
messaging.onBackgroundMessage((payload) => {
  console.log('[SW] onBackgroundMessage:', payload);

  const title = (payload.notification && payload.notification.title) || '\uD83D\uDD14 Market-U';
  const body = (payload.notification && payload.notification.body) || 'You have a new notification';

  self.registration.showNotification(title, {
    body: body,
    icon: '/icon.png',
    badge: '/icon.png',
    vibrate: [200, 100, 200, 100, 200],
    requireInteraction: true,
    tag: 'market-u-interest',
    data: payload.data || {},
  });
});

// Fallback: raw push event in case FCM messaging doesn't catch it
self.addEventListener('push', (event) => {
  console.log('[SW] raw push event:', event);
  if (!event.data) return;

  let payload = {};
  try { payload = event.data.json(); } catch(e) {}

  const title = (payload.notification && payload.notification.title) || '\uD83D\uDD14 Market-U';
  const body = (payload.notification && payload.notification.body) || 'Someone is interested in your product!';

  event.waitUntil(
    self.registration.showNotification(title, {
      body: body,
      icon: '/icon.png',
      badge: '/icon.png',
      vibrate: [200, 100, 200, 100, 200],
      requireInteraction: true,
      tag: 'market-u-interest',
    })
  );
});

// Open app to /notifications when notification is clicked
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] notificationclick');
  event.notification.close();
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus();
          client.navigate('/notifications');
          return;
        }
      }
      if (clients.openWindow) {
        return clients.openWindow('/notifications');
      }
    })
  );
});
`

      const outPath = path.resolve(config.root, 'public', 'firebase-messaging-sw.js')
      fs.writeFileSync(outPath, swContent, 'utf-8')
      console.log('✅ firebase-messaging-sw.js generated from env vars')
    }
  }
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  return {
    plugins: [react(), firebaseSwPlugin()],
  }
})
